### ISSUE TITLE
Ability to ignore certain packages. example ( --ignore babel-core )

### ISSUE THREAD

**Issue by nreoch9** [ahmadnassri/node-updated#2]
Currently the official latest version of babel-core is 6.26.3 however babel-jest requires babel-core@^7.0.0-0 in order to run jest tests.  Could we possibly add a feature where we could ignore some deps from being run against this.  ie. npx updated --ignore babel-core.

Thanks
Nigel

**Comment by ahmadnassri** [comment]
good idea!

**Comment by ahmadnassri** [comment]
shipped!
